.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, recipe/meta.yaml
=> lalsuite v6.53

recipe/build.sh, recipe/meta.yaml
Checklist
Update lalsuite to v6.64, with lalinference 1.11.5
=> Update to lalsuite 6.64

recipe/meta.yaml
Update to latest `lalburst`.
Checklist
=> lalsuite v6.65

recipe/meta.yaml
Bump for new lalapps.
Checklist
=> lalsuite v6.66

recipe/meta.yaml
Bump for new lalsimulation.
Checklist
=> lalsuite v6.67

recipe/meta.yaml
=> lalsuite v6.69

.ci_support/linux_.yaml, recipe/meta.yaml
=> lalsuite v6.70

recipe/meta.yaml
=> lalsuite v6.72

recipe/meta.yaml
=> lalsuite 6.74

.scripts/build_steps.sh, recipe/meta.yaml
=> lalsuite 6.76

recipe/meta.yaml
=> lalsuite 6.77

recipe/meta.yaml
=> lalsuite 6.78

recipe/meta.yaml
=> lalsuite v6.79

recipe/meta.yaml
for lalsimulation 2.4.0
Checklist
=> lalsuite 6.80

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, build-locally.py, recipe/meta.yaml
=> Lalsuite 6.81

README.md, recipe/meta.yaml
=> lalsuite v6.82

recipe/meta.yaml
=> lalsuite v7.0

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .gitattributes, .scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, LICENSE.txt, README.md, build-locally.py, recipe/meta.yaml
=> lalsuite v7.1

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, recipe/meta.yaml
=> lalsuite v7.2

recipe/meta.yaml
=> lalsuite v7.3

.azure-pipelines/azure-pipelines-linux.yml, recipe/meta.yaml
=> Lalsuite v7.19
